spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cart?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    port: 6379
    host: localhost
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 1
    timeout: 1000
server:
  port: 80
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml